# Generated by Django 2.1.3 on 2019-05-27 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190321_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Address_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Parish',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='TRN',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
